from .models import (
    BloomLevel,
    PaperPattern,
    QuestionKind,
    SectionPattern,
    SubpartPattern,
)


def default_college_pattern() -> PaperPattern:
    """Return the 80-mark pattern derived from pdfs/test_paper.pdf."""
    return PaperPattern(
        pattern_id="sample-paper-80-v2",
        name="Five-Section 80 Mark Sample-Paper Pattern",
        duration_minutes=180,
        total_marks=80,
        sections=[
            SectionPattern(
                section_id="section_a",
                title="Section A — MCQ and Assertion–Reason",
                question_kind=QuestionKind.MULTIPLE_CHOICE,
                question_count=20,
                marks_each=1,
                visual_question_count=1,
                bloom_sequence=[
                    *([BloomLevel.REMEMBER] * 6),
                    *([BloomLevel.UNDERSTAND] * 6),
                    *([BloomLevel.APPLY] * 5),
                    *([BloomLevel.ANALYZE] * 3),
                ],
                question_kind_sequence=[
                    *([QuestionKind.MULTIPLE_CHOICE] * 18),
                    QuestionKind.ASSERTION_REASON,
                    QuestionKind.ASSERTION_REASON,
                ],
            ),
            SectionPattern(
                section_id="section_b",
                title="Section B — Very Short Answer",
                question_kind=QuestionKind.VERY_SHORT_ANSWER,
                question_count=5,
                marks_each=2,
                choices_per_question=2,
                answers_required=1,
                internal_choice_count=2,
                internal_choice_positions=[2, 3],
                bloom_sequence=[
                    BloomLevel.UNDERSTAND,
                    BloomLevel.UNDERSTAND,
                    BloomLevel.APPLY,
                    BloomLevel.APPLY,
                    BloomLevel.ANALYZE,
                ],
            ),
            SectionPattern(
                section_id="section_c",
                title="Section C — Short Answer",
                question_kind=QuestionKind.SHORT_ANSWER,
                question_count=6,
                marks_each=3,
                visual_question_count=1,
                choices_per_question=2,
                answers_required=1,
                internal_choice_count=2,
                internal_choice_positions=[1, 3],
                bloom_sequence=[
                    BloomLevel.APPLY,
                    BloomLevel.APPLY,
                    BloomLevel.APPLY,
                    BloomLevel.ANALYZE,
                    BloomLevel.ANALYZE,
                    BloomLevel.ANALYZE,
                ],
            ),
            SectionPattern(
                section_id="section_d",
                title="Section D — Long Answer",
                question_kind=QuestionKind.LONG_ANSWER,
                question_count=4,
                marks_each=5,
                visual_question_count=1,
                choices_per_question=2,
                answers_required=1,
                internal_choice_count=2,
                internal_choice_positions=[2, 3],
                bloom_sequence=[
                    BloomLevel.ANALYZE,
                    BloomLevel.ANALYZE,
                    BloomLevel.EVALUATE,
                    BloomLevel.CREATE,
                ],
            ),
            SectionPattern(
                section_id="section_e",
                title="Section E — Case Study",
                question_kind=QuestionKind.CASE_STUDY,
                question_count=3,
                marks_each=4,
                visual_question_count=1,
                choices_per_question=2,
                answers_required=1,
                internal_choice_count=3,
                internal_choice_positions=[1, 2, 3],
                internal_choice_scope="final_subpart",
                subparts=[
                    SubpartPattern(label="(i)", marks=1),
                    SubpartPattern(label="(ii)", marks=1),
                    SubpartPattern(label="(iii)", marks=2),
                ],
                bloom_sequence=[
                    BloomLevel.APPLY,
                    BloomLevel.ANALYZE,
                    BloomLevel.EVALUATE,
                ],
            ),
        ],
    )
