import { useMemo, useState } from "react";

import type {
  DemoPaperStatus,
  DemoPaperSummary,
  DemoRole,
  DemoUser,
} from "../../types/api";

const STATUS_LABELS: Record<DemoPaperStatus, string> = {
  draft: "Faculty draft",
  faculty_finalized: "Ready to send",
  submitted_to_hod: "HOD review",
  submitted_to_coe: "CoE review",
  approved: "Approved",
};

const ROLE_QUEUE: Record<DemoRole, DemoPaperStatus[]> = {
  faculty: ["draft"],
  hod: ["submitted_to_hod"],
  coe: ["submitted_to_coe"],
};

const PAGE_COPY: Record<
  DemoRole,
  Record<"queue" | "history", { title: string; description: string }>
> = {
  faculty: {
    queue: {
      title: "Drafts",
      description:
        "Working papers that can still be edited or regenerated before submission.",
    },
    history: {
      title: "Generated question papers",
      description:
        "Locked papers in the official format. Send them to the HOD from inside the paper view.",
    },
  },
  hod: {
    queue: {
      title: "Department approval queue",
      description:
        "Faculty submissions awaiting review. Open one to compare and forward a set.",
    },
    history: {
      title: "Department paper history",
      description:
        "Every paper generated across the department and who is responsible for it.",
    },
  },
  coe: {
    queue: {
      title: "Final examination review",
      description:
        "HOD-selected papers awaiting a final accept or decline decision.",
    },
    history: {
      title: "CoE decision history",
      description: "Accepted papers and papers returned for revision.",
    },
  },
};

type ChipKey =
  | "all"
  | "draft"
  | "faculty_finalized"
  | "review"
  | "submitted_to_hod"
  | "submitted_to_coe"
  | "approved"
  | "declined";

const CHIP_META: Record<ChipKey, { label: string; dot?: string }> = {
  all: { label: "All" },
  draft: { label: "To do", dot: "var(--warning)" },
  faculty_finalized: { label: "Ready to send", dot: "var(--brand-1)" },
  review: { label: "In progress", dot: "var(--brand-1)" },
  submitted_to_hod: { label: "In progress", dot: "var(--warning)" },
  submitted_to_coe: { label: "In progress", dot: "var(--warning)" },
  approved: { label: "Completed", dot: "var(--green)" },
  declined: { label: "Returned", dot: "var(--destructive)" },
};

const CHIP_ORDER: ChipKey[] = [
  "all",
  "draft",
  "faculty_finalized",
  "review",
  "submitted_to_hod",
  "submitted_to_coe",
  "approved",
  "declined",
];

const PILL_CLASS: Record<ChipKey, string> = {
  all: "",
  draft: "filter-status-todo",
  faculty_finalized: "filter-status-ready",
  review: "filter-status-progress",
  submitted_to_hod: "filter-status-progress",
  submitted_to_coe: "filter-status-progress",
  approved: "filter-status-done",
  declined: "filter-status-returned",
};

function paperChip(paper: DemoPaperSummary, role: DemoRole, mode: "queue" | "history"): ChipKey {
  if (
    role === "coe" &&
    mode === "history" &&
    paper.last_coe_action === "decline" &&
    paper.status !== "approved"
  ) {
    return "declined";
  }
  if (
    role === "faculty" &&
    mode === "history" &&
    (paper.status === "submitted_to_hod" || paper.status === "submitted_to_coe")
  ) {
    return "review";
  }
  return paper.status;
}

function pillFor(paper: DemoPaperSummary, role: DemoRole, mode: "queue" | "history") {
  const key = paperChip(paper, role, mode);
  if (key === "declined") return { label: "Returned", cls: PILL_CLASS.declined };
  if (key === "review") return { label: "In progress", cls: PILL_CLASS.review };
  if (key === "draft") return { label: "To do", cls: PILL_CLASS.draft };
  if (key === "faculty_finalized") return { label: "Ready to send", cls: PILL_CLASS.faculty_finalized };
  if (key === "approved") return { label: "Completed", cls: PILL_CLASS.approved };
  if (key === "submitted_to_hod" || key === "submitted_to_coe") {
    return { label: "In progress", cls: PILL_CLASS[key] };
  }
  return { label: STATUS_LABELS[paper.status], cls: PILL_CLASS[paper.status] };
}

function ownerHeading(role: DemoRole): string {
  if (role === "hod") return "Generated by";
  if (role === "coe") return "Department";
  return "Examination";
}

function ownerValue(paper: DemoPaperSummary, role: DemoRole): string {
  if (role === "hod") return paper.generated_by || "Faculty not recorded";
  if (role === "coe") return paper.department || "Department not recorded";
  return paper.exam_label;
}

function formatShortDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "\u2014";
  return new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
  }).format(date);
}

function formatFullDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

interface PaperListPageProps {
  mode: "queue" | "history";
  user: DemoUser;
  papers: DemoPaperSummary[];
  loading: boolean;
  error: string | null;
  onOpen: (paperId: string) => void;
  onRefresh: () => void;
}

export function PaperListPage({
  mode,
  user,
  papers,
  loading,
  error,
  onOpen,
  onRefresh,
}: PaperListPageProps) {
  const [query, setQuery] = useState("");
  const [subject, setSubject] = useState("all");
  const [year, setYear] = useState("all");
  const [department, setDepartment] = useState("all");
  const [examination, setExamination] = useState("all");
  const [status, setStatus] = useState<ChipKey>("all");
  const copy = PAGE_COPY[user.role][mode];

  const accessiblePapers =
    user.role === "faculty"
      ? papers.filter(
          (paper) =>
            !paper.generated_by || paper.generated_by === user.displayName,
        )
      : user.role === "hod"
        ? papers.filter(
            (paper) => !["draft", "faculty_finalized"].includes(paper.status),
          )
        : papers.filter(
            (paper) =>
              ["submitted_to_coe", "approved"].includes(paper.status) ||
              Boolean(paper.last_coe_action),
          );

  let rolePapers = accessiblePapers;
  if (user.role === "faculty" && mode === "history") {
    rolePapers = accessiblePapers.filter((paper) => paper.status !== "draft");
  } else if (user.role === "coe" && mode === "history") {
    rolePapers = accessiblePapers.filter(
      (paper) =>
        paper.status === "approved" || paper.last_coe_action === "decline",
    );
  }
  if (mode === "queue") {
    rolePapers = rolePapers.filter((paper) =>
      ROLE_QUEUE[user.role].includes(paper.status),
    );
  }

  const subjects = [
    ...new Set(
      rolePapers.map((paper) => paper.course_name || paper.subject).filter(Boolean),
    ),
  ].sort();
  const departments = [
    ...new Set(rolePapers.map((paper) => paper.department).filter(Boolean)),
  ].sort();
  const examinations = [
    ...new Set(rolePapers.map((paper) => paper.exam_label).filter(Boolean)),
  ].sort();
  const years = [
    ...new Set(rolePapers.map((paper) => paper.year).filter(Boolean)),
  ].sort();

  const search = query.trim().toLowerCase();
  const searched = rolePapers.filter(
    (paper) =>
      (search === "" ||
        [
          paper.course_code,
          paper.course_name,
          paper.subject,
          paper.exam_label,
          paper.generated_by,
        ]
          .join(" ")
          .toLowerCase()
          .includes(search)) &&
      (subject === "all" || (paper.course_name || paper.subject) === subject) &&
      (year === "all" || paper.year === year) &&
      (department === "all" || paper.department === department) &&
      (examination === "all" || paper.exam_label === examination),
  );

  const chipCounts = useMemo(() => {
    const counts = new Map<ChipKey, number>();
    searched.forEach((paper) => {
      const key = paperChip(paper, user.role, mode);
      counts.set(key, (counts.get(key) ?? 0) + 1);
    });
    return counts;
  }, [searched, user.role, mode]);

  const chips = CHIP_ORDER.filter(
    (key) => key === "all" || (chipCounts.get(key) ?? 0) > 0,
  ).map((key) => ({
    key,
    label: CHIP_META[key].label,
    dot: CHIP_META[key].dot,
    count: key === "all" ? searched.length : (chipCounts.get(key) ?? 0),
  }));

  const visibleCount =
    status === "all" ? searched.length : (chipCounts.get(status) ?? 0);

  const filtersActive =
    search !== "" ||
    subject !== "all" ||
    year !== "all" ||
    department !== "all" ||
    examination !== "all" ||
    status !== "all";

  const openPaper = (paperId: string) => onOpen(paperId);

  return (
    <main className="demo-page page-container">
      <div className="demo-page-heading">
        <div>
          <h1>{copy.title}</h1>
          <p>{copy.description}</p>
        </div>
        <button className="secondary-button" onClick={onRefresh} type="button">
          Refresh
        </button>
      </div>

      <div className="paper-toolbar">
        <label className="paper-search">
          <span className="visually-hidden">Search papers</span>
          <input
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search course code, subject, or examination"
            type="search"
            value={query}
          />
        </label>
        {subjects.length > 1 && (
          <label className="paper-filter">
            <span>Subject</span>
            <select onChange={(event) => setSubject(event.target.value)} value={subject}>
              <option value="all">All subjects</option>
              {subjects.map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          </label>
        )}
        {user.role === "coe" && departments.length > 1 && (
          <label className="paper-filter">
            <span>Department</span>
            <select
              onChange={(event) => setDepartment(event.target.value)}
              value={department}
            >
              <option value="all">All departments</option>
              {departments.map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          </label>
        )}
        {user.role === "coe" && years.length > 1 && (
          <label className="paper-filter">
            <span>Academic year</span>
            <select onChange={(event) => setYear(event.target.value)} value={year}>
              <option value="all">All years</option>
              {years.map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          </label>
        )}
        {user.role === "coe" && examinations.length > 1 && (
          <label className="paper-filter">
            <span>Examination</span>
            <select
              onChange={(event) => setExamination(event.target.value)}
              value={examination}
            >
              <option value="all">All examinations</option>
              {examinations.map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          </label>
        )}
      </div>

      {error && (
        <div className="request-error" role="alert">
          {error}
        </div>
      )}

      {loading ? (
        <div aria-live="polite" className="paper-empty">
          <p>Loading papers{"\u2026"}</p>
        </div>
      ) : searched.length === 0 ? (
        <div className="paper-empty">
          <span aria-hidden="true" className="paper-empty-icon">
            <svg fill="none" height="20" viewBox="0 0 20 20" width="20">
              <path
                d="M5 2.5h7l3.5 3.5v11.5H5z"
                stroke="currentColor"
                strokeLinejoin="round"
                strokeWidth="1.4"
              />
              <path
                d="M12 2.5V6h3.5M7.5 10h5M7.5 13h5"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="1.4"
              />
            </svg>
          </span>
          <strong>
            {filtersActive ? "No papers match these filters" : "Nothing here yet"}
          </strong>
          <p>
            {filtersActive
              ? "Try clearing the search or widening the filters."
              : mode === "queue"
                ? "New papers appear here as soon as they reach this stage."
                : "Generated papers appear here once a draft is locked in."}
          </p>
        </div>
      ) : (
        <div className="paper-filter-table">
          <div
            className="paper-filter-chips"
            role="toolbar"
            aria-label="Filter by status"
            style={{ scrollbarWidth: "none" }}
          >
            {chips.map((chip) => {
              const active = status === chip.key;
              return (
                <button
                  aria-pressed={active}
                  className={
                    active
                      ? "paper-filter-chip is-active"
                      : "paper-filter-chip"
                  }
                  key={chip.key}
                  onClick={() => setStatus(chip.key)}
                  type="button"
                >
                  {chip.dot ? (
                    <span
                      aria-hidden="true"
                      className="paper-filter-chip-dot"
                      style={{ background: chip.dot }}
                    />
                  ) : null}
                  {chip.label}
                  <span className="paper-filter-chip-count">{chip.count}</span>
                </button>
              );
            })}
          </div>

          <div
            aria-label="Scrollable paper table"
            className="paper-grid"
            role="region"
            tabIndex={0}
            style={{ scrollbarWidth: "none" }}
          >
            <div className="paper-grid-inner">
              <div className="paper-grid-head" role="row">
                <span role="columnheader">Course</span>
                <span role="columnheader">Date</span>
                <span role="columnheader">Status</span>
                <span role="columnheader">{ownerHeading(user.role)}</span>
              </div>
              {searched.map((paper) => {
                const shown = status === "all" || paperChip(paper, user.role, mode) === status;
                const pill = pillFor(paper, user.role, mode);
                return (
                  <div
                    className="paper-grid-slot"
                    key={paper.id}
                    style={{
                      gridTemplateRows: shown ? "1fr" : "0fr",
                      opacity: shown ? 1 : 0,
                    }}
                  >
                    <div className="paper-grid-slot-inner">
                      <button
                        className="paper-grid-row"
                        onClick={() => openPaper(paper.id)}
                        tabIndex={shown ? 0 : -1}
                        type="button"
                      >
                        <span className="paper-grid-course">
                          <span className="paper-grid-course-name">
                            {paper.course_name || paper.subject}
                          </span>
                          <span className="paper-grid-course-code">
                            {paper.course_code || "Course code not set"}
                          </span>
                        </span>
                        <span
                          className="paper-grid-date"
                          title={formatFullDate(paper.updated_at)}
                        >
                          {formatShortDate(paper.updated_at)}
                        </span>
                        <span>
                          <span className={`paper-status-pill ${pill.cls}`}>
                            {pill.label}
                          </span>
                        </span>
                        <span className="paper-grid-owner">
                          {ownerValue(paper, user.role)}
                        </span>
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
          <p aria-live="polite" className="visually-hidden">
            {visibleCount} {visibleCount === 1 ? "paper" : "papers"} shown
          </p>
        </div>
      )}
    </main>
  );
}
